"""one report per session, plus the indexes the hot lookups actually need

Revision ID: a7c21d4b9e30
Revises: f3ba845e1e22
Create Date: 2026-08-06 16:20:00.000000

Hand-written rather than autogenerated (see AGENT.md): the unique constraint
cannot simply be added. Any session that was completed twice before this already
has two report rows, and `create_unique_constraint` on that data fails the
migration — which, because docker-compose runs `alembic upgrade head` as the api
command, would stop the API from booting at all. The duplicates are collapsed
first, keeping the earliest row.

Why each piece:

* `uq_session_reports_session_id` — `GET /api/interviews/{id}/report` uses
  `scalar_one_or_none()`, which raises MultipleResultsFound on two rows. That is
  a permanent 500 for the affected user with no recovery path. The constraint
  also provides the index for the outer join in every `GET /api/interviews`.
* `idx_matches_job` — the existing composite `(resume_id, job_id)` cannot serve a
  lookup keyed on job_id alone, which is what the matches list join does.
* `idx_interview_turns_session_turn` — `get_turn` filters on exactly this pair on
  every answer submission; only `session_id` was indexed.
* `matches.updated_at` — lets a stale-match sweep distinguish "queued a moment
  ago" from "the worker died holding this". Backfilled from created_at so
  existing rows aren't all reported as just-touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a7c21d4b9e30'
down_revision: Union[str, None] = 'f3ba845e1e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Collapse pre-existing duplicates before the constraint can reject them.
    # Earliest row wins: it is the one the user has already been shown, and both
    # were derived from the same finished set of turns anyway.
    op.execute(
        """
        DELETE FROM session_reports a
        USING session_reports b
        WHERE a.session_id = b.session_id
          AND (a.created_at, a.id) > (b.created_at, b.id)
        """
    )
    op.create_unique_constraint(
        "uq_session_reports_session_id", "session_reports", ["session_id"]
    )

    op.create_index("idx_matches_job", "matches", ["job_id"])
    op.create_index(
        "idx_interview_turns_session_turn", "interview_turns", ["session_id", "turn_number"]
    )

    op.add_column(
        "matches",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute("UPDATE matches SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column(
        "matches",
        "updated_at",
        nullable=False,
        server_default=sa.text("now()"),
    )


def downgrade() -> None:
    op.drop_column("matches", "updated_at")
    op.drop_index("idx_interview_turns_session_turn", table_name="interview_turns")
    op.drop_index("idx_matches_job", table_name="matches")
    op.drop_constraint(
        "uq_session_reports_session_id", "session_reports", type_="unique"
    )
