"""application tracking on job descriptions

Revision ID: b8e35f1c07a4
Revises: a7c21d4b9e30
Create Date: 2026-08-07 10:40:00.000000

Turns `job_descriptions` from a write-once record into an application pipeline.

Hand-written rather than autogenerated (see AGENT.md). Two things autogenerate
would get wrong:

* `status` and `priority` are NOT NULL. Existing rows have neither, so they are
  added nullable, backfilled, and only then tightened — adding a NOT NULL column
  without a server default to a populated table fails outright, and because
  docker-compose runs `alembic upgrade head` as the api command, a failed
  migration means the API does not boot.
* `updated_at` is backfilled from `created_at` rather than `now()`, so existing
  jobs don't all sort to the top of a list that is newly ordered by it.

Dates, not timestamps, for `applied_at` / `deadline`: "applied on the 3rd" and
"closes Friday" have no meaningful time of day, and storing them as instants
would shift the displayed day across timezones.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b8e35f1c07a4'
down_revision: Union[str, None] = 'a7c21d4b9e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("job_descriptions", sa.Column("status", sa.String(), nullable=True))
    op.add_column("job_descriptions", sa.Column("priority", sa.String(), nullable=True))
    op.add_column("job_descriptions", sa.Column("applied_at", sa.Date(), nullable=True))
    op.add_column("job_descriptions", sa.Column("deadline", sa.Date(), nullable=True))
    op.add_column("job_descriptions", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("job_descriptions", sa.Column("source_url", sa.Text(), nullable=True))
    op.add_column(
        "job_descriptions", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    op.execute("UPDATE job_descriptions SET status = 'saved' WHERE status IS NULL")
    op.execute("UPDATE job_descriptions SET priority = 'normal' WHERE priority IS NULL")
    op.execute("UPDATE job_descriptions SET updated_at = created_at WHERE updated_at IS NULL")

    op.alter_column(
        "job_descriptions", "status", nullable=False, server_default=sa.text("'saved'")
    )
    op.alter_column(
        "job_descriptions", "priority", nullable=False, server_default=sa.text("'normal'")
    )
    op.alter_column(
        "job_descriptions", "updated_at", nullable=False, server_default=sa.text("now()")
    )

    # The board groups by status per user; this is the exact lookup.
    op.create_index("idx_jobs_user_status", "job_descriptions", ["user_id", "status"])


def downgrade() -> None:
    op.drop_index("idx_jobs_user_status", table_name="job_descriptions")
    for column in (
        "updated_at",
        "source_url",
        "notes",
        "deadline",
        "applied_at",
        "priority",
        "status",
    ):
        op.drop_column("job_descriptions", column)
